### ISSUE TITLE
Separação dos bots

### ISSUE THREAD

**Issue by PauloLuan** [databr/bots#18]
Deixar os bots em único repositório é uma boa?

Pensei em fazer deste repositório um centralizador de deploys de forma a usar submódulos talvez com todos os crawlers já feitos por outros usuários. Isso facilitaria a contribuição e descentralização dos códigos, pois o pull request seria: 
- Adição da url do repositório do bot que ele desenvolveu no nosso .gitmodules. Como no exemplo: 
  
  ```
  [submodule "gobot/nomedobot"]
  
  path = gobot/nomedobot
  
  url = git://github.com/dukex/nomedobot.git
  ```
- Adição das informações no MakeFile pro build no servidor remoto.

Por exemplo, se eu desenvolvesse um bot comum eu gostaria que meu projeto usasse travis, coveralls, codeship e etc, e alguns desses serviços clonam diretamente o repositório, dificultando a integração, visto que o repositório está inserido internamente ao projeto principal.

**Comment by dukex** [comment]
Eu acho muito valido isso, vou mover os bots atuais,
mas acho que o processo de deploy tem que ser melhor pensado.

**Comment by dukex** [comment]
- [ ] ~~ibge-bot~~ https://github.com/databr/ibge-bot
- [ ] metrosp_bot
- [ ] parliamentarian_bot
- [ ] sabesp_bot

**Comment by dukex** [comment]
2 coisas que precisa ser definido e então faço os pull-requests  

- [ ] Framework para Deploy
- [ ] Forma de testar a integração

**Comment by dukex** [comment]
@PauloLuan para possibilitar bots privados seria melhor usar um yaml ou json que falasse os repositórios e um script leria e tentaria clonar

**Comment by PauloLuan** [comment]
Ow, o private aqui é fake? não é informação sensitiva?

https://github.com/databr/bots/blob/master/.env.development

**Comment by dukex** [comment]
esse arquivo é fake sim

**Comment by PauloLuan** [comment]
Submódulos é um tanto quanto problemático.

Essa idéia do yml é boa, talvez esse processo de clonar ou dar pull nos repositórios teria que ser feito direto no servidor de produção, talvez automatizar isso com o docker. 

Como é feito o deploy lá?

**Comment by dukex** [comment]
1. O go gera um binario para linux, 
2. O makefile sobe via rsync o binario
3. Um job no jenkins roda periodicamente esse binario

Estou pensando em usar algo diferente do jenkins, mas que ainda sim de um report visual dos jobs, se conhecer algo da um toque

**Comment by dukex** [comment]
Fechando em favor do https://github.com/databr/bots/issues/19
